<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Country::truncate();

        $countries = array(
            array('sortname' => 'AF', 'name' => 'Afghanistan', 'slug' => 'afghanistan', 'phonecode' => '93', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AL', 'name' => 'Albania', 'slug' => 'albania', 'phonecode' => '355', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'DZ', 'name' => 'Algeria', 'slug' => 'algeria', 'phonecode' => '213', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AS', 'name' => 'American Samoa', 'slug' => 'american-samoa', 'phonecode' => '1684', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AD', 'name' => 'Andorra', 'slug' => 'andorra', 'phonecode' => '376', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AO', 'name' => 'Angola', 'slug' => 'angola', 'phonecode' => '244', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AI', 'name' => 'Anguilla', 'slug' => 'anguilla', 'phonecode' => '1264', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AQ', 'name' => 'Antarctica', 'slug' => 'antarctica', 'phonecode' => '0', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AG', 'name' => 'Antigua And Barbuda', 'slug' => 'antigua-and-barbuda', 'phonecode' => '1268', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AR', 'name' => 'Argentina', 'slug' => 'argentina', 'phonecode' => '54', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AM', 'name' => 'Armenia', 'slug' => 'armenia', 'phonecode' => '374', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AW', 'name' => 'Aruba', 'slug' => 'aruba', 'phonecode' => '297', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AU', 'name' => 'Australia', 'slug' => 'australia', 'phonecode' => '61', 'status' => '1', 'priority' => '5'),
            array('sortname' => 'AT', 'name' => 'Austria', 'slug' => 'austria', 'phonecode' => '43', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AZ', 'name' => 'Azerbaijan', 'slug' => 'azerbaijan', 'phonecode' => '994', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BS', 'name' => 'Bahamas The', 'slug' => 'bahamas-the', 'phonecode' => '1242', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BH', 'name' => 'Bahrain', 'slug' => 'bahrain', 'phonecode' => '973', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BD', 'name' => 'Bangladesh', 'slug' => 'bangladesh', 'phonecode' => '880', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BB', 'name' => 'Barbados', 'slug' => 'barbados', 'phonecode' => '1246', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BY', 'name' => 'Belarus', 'slug' => 'belarus', 'phonecode' => '375', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BE', 'name' => 'Belgium', 'slug' => 'belgium', 'phonecode' => '32', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BZ', 'name' => 'Belize', 'slug' => 'belize', 'phonecode' => '501', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BJ', 'name' => 'Benin', 'slug' => 'benin', 'phonecode' => '229', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BM', 'name' => 'Bermuda', 'slug' => 'bermuda', 'phonecode' => '1441', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BT', 'name' => 'Bhutan', 'slug' => 'bhutan', 'phonecode' => '975', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BO', 'name' => 'Bolivia', 'slug' => 'bolivia', 'phonecode' => '591', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BA', 'name' => 'Bosnia and Herzegovina', 'slug' => 'bosnia-and-herzegovina', 'phonecode' => '387', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BW', 'name' => 'Botswana', 'slug' => 'botswana', 'phonecode' => '267', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BV', 'name' => 'Bouvet Island', 'slug' => 'bouvet-island', 'phonecode' => '0', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BR', 'name' => 'Brazil', 'slug' => 'brazil', 'phonecode' => '55', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'IO', 'name' => 'British Indian Ocean Territory', 'slug' => 'british-indian-ocean-territory', 'phonecode' => '246', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BN', 'name' => 'Brunei', 'slug' => 'brunei', 'phonecode' => '673', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BG', 'name' => 'Bulgaria', 'slug' => 'bulgaria', 'phonecode' => '359', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BF', 'name' => 'Burkina Faso', 'slug' => 'burkina-faso', 'phonecode' => '226', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'BI', 'name' => 'Burundi', 'slug' => 'burundi', 'phonecode' => '257', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KH', 'name' => 'Cambodia', 'slug' => 'cambodia', 'phonecode' => '855', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CM', 'name' => 'Cameroon', 'slug' => 'cameroon', 'phonecode' => '237', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CA', 'name' => 'Canada', 'slug' => 'canada', 'phonecode' => '1', 'status' => '1', 'priority' => '4'),
            array('sortname' => 'CV', 'name' => 'Cape Verde', 'slug' => 'cape-verde', 'phonecode' => '238', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KY', 'name' => 'Cayman Islands', 'slug' => 'cayman-islands', 'phonecode' => '1345', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CF', 'name' => 'Central African Republic', 'slug' => 'central-african-republic', 'phonecode' => '236', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TD', 'name' => 'Chad', 'slug' => 'chad', 'phonecode' => '235', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CL', 'name' => 'Chile', 'slug' => 'chile', 'phonecode' => '56', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CN', 'name' => 'China', 'slug' => 'china', 'phonecode' => '86', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CX', 'name' => 'Christmas Island', 'slug' => 'christmas-island', 'phonecode' => '61', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'slug' => 'cocos-keeling-islands', 'phonecode' => '672', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CO', 'name' => 'Colombia', 'slug' => 'colombia', 'phonecode' => '57', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KM', 'name' => 'Comoros', 'slug' => 'comoros', 'phonecode' => '269', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CG', 'name' => 'Republic Of The Congo', 'slug' => 'republic-of-the-congo', 'phonecode' => '242', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CD', 'name' => 'Democratic Republic Of The Congo', 'slug' => 'democratic-republic-of-the-congo', 'phonecode' => '242', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CK', 'name' => 'Cook Islands', 'slug' => 'cook-islands', 'phonecode' => '682', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CR', 'name' => 'Costa Rica', 'slug' => 'costa-rica', 'phonecode' => '506', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CI', 'name' => 'Cote D\'Ivoire (Ivory Coast)', 'slug' => 'cote-divoire-ivory-coast', 'phonecode' => '225', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'HR', 'name' => 'Croatia (Hrvatska)', 'slug' => 'croatia-hrvatska', 'phonecode' => '385', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CU', 'name' => 'Cuba', 'slug' => 'cuba', 'phonecode' => '53', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CY', 'name' => 'Cyprus', 'slug' => 'cyprus', 'phonecode' => '357', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CZ', 'name' => 'Czech Republic', 'slug' => 'czech-republic', 'phonecode' => '420', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'DK', 'name' => 'Denmark', 'slug' => 'denmark', 'phonecode' => '45', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'DJ', 'name' => 'Djibouti', 'slug' => 'djibouti', 'phonecode' => '253', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'DM', 'name' => 'Dominica', 'slug' => 'dominica', 'phonecode' => '1767', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'DO', 'name' => 'Dominican Republic', 'slug' => 'dominican-republic', 'phonecode' => '1809', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TP', 'name' => 'East Timor', 'slug' => 'east-timor', 'phonecode' => '670', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'EC', 'name' => 'Ecuador', 'slug' => 'ecuador', 'phonecode' => '593', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'EG', 'name' => 'Egypt', 'slug' => 'egypt', 'phonecode' => '20', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SV', 'name' => 'El Salvador', 'slug' => 'el-salvador', 'phonecode' => '503', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GQ', 'name' => 'Equatorial Guinea', 'slug' => 'equatorial-guinea', 'phonecode' => '240', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'ER', 'name' => 'Eritrea', 'slug' => 'eritrea', 'phonecode' => '291', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'EE', 'name' => 'Estonia', 'slug' => 'estonia', 'phonecode' => '372', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'ET', 'name' => 'Ethiopia', 'slug' => 'ethiopia', 'phonecode' => '251', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'XA', 'name' => 'External Territories of Australia', 'slug' => 'external-territories-of-australia', 'phonecode' => '61', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'FK', 'name' => 'Falkland Islands', 'slug' => 'falkland-islands', 'phonecode' => '500', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'FO', 'name' => 'Faroe Islands', 'slug' => 'faroe-islands', 'phonecode' => '298', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'FJ', 'name' => 'Fiji Islands', 'slug' => 'fiji-islands', 'phonecode' => '679', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'FI', 'name' => 'Finland', 'slug' => 'finland', 'phonecode' => '358', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'FR', 'name' => 'France', 'slug' => 'france', 'phonecode' => '33', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GF', 'name' => 'French Guiana', 'slug' => 'french-guiana', 'phonecode' => '594', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PF', 'name' => 'French Polynesia', 'slug' => 'french-polynesia', 'phonecode' => '689', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TF', 'name' => 'French Southern Territories', 'slug' => 'french-southern-territories', 'phonecode' => '0', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GA', 'name' => 'Gabon', 'slug' => 'gabon', 'phonecode' => '241', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GM', 'name' => 'Gambia The', 'slug' => 'gambia-the', 'phonecode' => '220', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GE', 'name' => 'Georgia', 'slug' => 'georgia', 'phonecode' => '995', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'DE', 'name' => 'Germany', 'slug' => 'germany', 'phonecode' => '49', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GH', 'name' => 'Ghana', 'slug' => 'ghana', 'phonecode' => '233', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GI', 'name' => 'Gibraltar', 'slug' => 'gibraltar', 'phonecode' => '350', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GR', 'name' => 'Greece', 'slug' => 'greece', 'phonecode' => '30', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GL', 'name' => 'Greenland', 'slug' => 'greenland', 'phonecode' => '299', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GD', 'name' => 'Grenada', 'slug' => 'grenada', 'phonecode' => '1473', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GP', 'name' => 'Guadeloupe', 'slug' => 'guadeloupe', 'phonecode' => '590', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GU', 'name' => 'Guam', 'slug' => 'guam', 'phonecode' => '1671', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GT', 'name' => 'Guatemala', 'slug' => 'guatemala', 'phonecode' => '502', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'XU', 'name' => 'Guernsey and Alderney', 'slug' => 'guernsey-and-alderney', 'phonecode' => '44', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GN', 'name' => 'Guinea', 'slug' => 'guinea', 'phonecode' => '224', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GW', 'name' => 'Guinea-Bissau', 'slug' => 'guineabissau', 'phonecode' => '245', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GY', 'name' => 'Guyana', 'slug' => 'guyana', 'phonecode' => '592', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'HT', 'name' => 'Haiti', 'slug' => 'haiti', 'phonecode' => '509', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'HM', 'name' => 'Heard and McDonald Islands', 'slug' => 'heard-and-mcdonald-islands', 'phonecode' => '0', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'HN', 'name' => 'Honduras', 'slug' => 'honduras', 'phonecode' => '504', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'HK', 'name' => 'Hong Kong S.A.R.', 'slug' => 'hong-kong-sar', 'phonecode' => '852', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'HU', 'name' => 'Hungary', 'slug' => 'hungary', 'phonecode' => '36', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'IS', 'name' => 'Iceland', 'slug' => 'iceland', 'phonecode' => '354', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'IN', 'name' => 'India', 'slug' => 'india', 'phonecode' => '91', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'ID', 'name' => 'Indonesia', 'slug' => 'indonesia', 'phonecode' => '62', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'IR', 'name' => 'Iran', 'slug' => 'iran', 'phonecode' => '98', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'IQ', 'name' => 'Iraq', 'slug' => 'iraq', 'phonecode' => '964', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'IE', 'name' => 'Ireland', 'slug' => 'ireland', 'phonecode' => '353', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'IL', 'name' => 'Israel', 'slug' => 'israel', 'phonecode' => '972', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'IT', 'name' => 'Italy', 'slug' => 'italy', 'phonecode' => '39', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'JM', 'name' => 'Jamaica', 'slug' => 'jamaica', 'phonecode' => '1876', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'JP', 'name' => 'Japan', 'slug' => 'japan', 'phonecode' => '81', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'XJ', 'name' => 'Jersey', 'slug' => 'jersey', 'phonecode' => '44', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'JO', 'name' => 'Jordan', 'slug' => 'jordan', 'phonecode' => '962', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KZ', 'name' => 'Kazakhstan', 'slug' => 'kazakhstan', 'phonecode' => '7', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KE', 'name' => 'Kenya', 'slug' => 'kenya', 'phonecode' => '254', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KI', 'name' => 'Kiribati', 'slug' => 'kiribati', 'phonecode' => '686', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KP', 'name' => 'Korea North', 'slug' => 'korea-north', 'phonecode' => '850', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KR', 'name' => 'Korea South', 'slug' => 'korea-south', 'phonecode' => '82', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KW', 'name' => 'Kuwait', 'slug' => 'kuwait', 'phonecode' => '965', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KG', 'name' => 'Kyrgyzstan', 'slug' => 'kyrgyzstan', 'phonecode' => '996', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LA', 'name' => 'Laos', 'slug' => 'laos', 'phonecode' => '856', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LV', 'name' => 'Latvia', 'slug' => 'latvia', 'phonecode' => '371', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LB', 'name' => 'Lebanon', 'slug' => 'lebanon', 'phonecode' => '961', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LS', 'name' => 'Lesotho', 'slug' => 'lesotho', 'phonecode' => '266', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LR', 'name' => 'Liberia', 'slug' => 'liberia', 'phonecode' => '231', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LY', 'name' => 'Libya', 'slug' => 'libya', 'phonecode' => '218', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LI', 'name' => 'Liechtenstein', 'slug' => 'liechtenstein', 'phonecode' => '423', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LT', 'name' => 'Lithuania', 'slug' => 'lithuania', 'phonecode' => '370', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LU', 'name' => 'Luxembourg', 'slug' => 'luxembourg', 'phonecode' => '352', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MO', 'name' => 'Macau S.A.R.', 'slug' => 'macau-sar', 'phonecode' => '853', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MK', 'name' => 'Macedonia', 'slug' => 'macedonia', 'phonecode' => '389', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MG', 'name' => 'Madagascar', 'slug' => 'madagascar', 'phonecode' => '261', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MW', 'name' => 'Malawi', 'slug' => 'malawi', 'phonecode' => '265', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MY', 'name' => 'Malaysia', 'slug' => 'malaysia', 'phonecode' => '60', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MV', 'name' => 'Maldives', 'slug' => 'maldives', 'phonecode' => '960', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'ML', 'name' => 'Mali', 'slug' => 'mali', 'phonecode' => '223', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MT', 'name' => 'Malta', 'slug' => 'malta', 'phonecode' => '356', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'XM', 'name' => 'Man (Isle of)', 'slug' => 'man-isle-of', 'phonecode' => '44', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MH', 'name' => 'Marshall Islands', 'slug' => 'marshall-islands', 'phonecode' => '692', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MQ', 'name' => 'Martinique', 'slug' => 'martinique', 'phonecode' => '596', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MR', 'name' => 'Mauritania', 'slug' => 'mauritania', 'phonecode' => '222', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MU', 'name' => 'Mauritius', 'slug' => 'mauritius', 'phonecode' => '230', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'YT', 'name' => 'Mayotte', 'slug' => 'mayotte', 'phonecode' => '269', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MX', 'name' => 'Mexico', 'slug' => 'mexico', 'phonecode' => '52', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'FM', 'name' => 'Micronesia', 'slug' => 'micronesia', 'phonecode' => '691', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MD', 'name' => 'Moldova', 'slug' => 'moldova', 'phonecode' => '373', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MC', 'name' => 'Monaco', 'slug' => 'monaco', 'phonecode' => '377', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MN', 'name' => 'Mongolia', 'slug' => 'mongolia', 'phonecode' => '976', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MS', 'name' => 'Montserrat', 'slug' => 'montserrat', 'phonecode' => '1664', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MA', 'name' => 'Morocco', 'slug' => 'morocco', 'phonecode' => '212', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MZ', 'name' => 'Mozambique', 'slug' => 'mozambique', 'phonecode' => '258', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MM', 'name' => 'Myanmar', 'slug' => 'myanmar', 'phonecode' => '95', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NA', 'name' => 'Namibia', 'slug' => 'namibia', 'phonecode' => '264', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NR', 'name' => 'Nauru', 'slug' => 'nauru', 'phonecode' => '674', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NP', 'name' => 'Nepal', 'slug' => 'nepal', 'phonecode' => '977', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AN', 'name' => 'Netherlands Antilles', 'slug' => 'netherlands-antilles', 'phonecode' => '599', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NL', 'name' => 'Netherlands The', 'slug' => 'netherlands-the', 'phonecode' => '31', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NC', 'name' => 'New Caledonia', 'slug' => 'new-caledonia', 'phonecode' => '687', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NZ', 'name' => 'New Zealand', 'slug' => 'new-zealand', 'phonecode' => '64', 'status' => '1', 'priority' => '3'),
            array('sortname' => 'NI', 'name' => 'Nicaragua', 'slug' => 'nicaragua', 'phonecode' => '505', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NE', 'name' => 'Niger', 'slug' => 'niger', 'phonecode' => '227', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NG', 'name' => 'Nigeria', 'slug' => 'nigeria', 'phonecode' => '234', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NU', 'name' => 'Niue', 'slug' => 'niue', 'phonecode' => '683', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NF', 'name' => 'Norfolk Island', 'slug' => 'norfolk-island', 'phonecode' => '672', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'MP', 'name' => 'Northern Mariana Islands', 'slug' => 'northern-mariana-islands', 'phonecode' => '1670', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'NO', 'name' => 'Norway', 'slug' => 'norway', 'phonecode' => '47', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'OM', 'name' => 'Oman', 'slug' => 'oman', 'phonecode' => '968', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PK', 'name' => 'Pakistan', 'slug' => 'pakistan', 'phonecode' => '92', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PW', 'name' => 'Palau', 'slug' => 'palau', 'phonecode' => '680', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PS', 'name' => 'Palestinian Territory Occupied', 'slug' => 'palestinian-territory-occupied', 'phonecode' => '970', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PA', 'name' => 'Panama', 'slug' => 'panama', 'phonecode' => '507', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PG', 'name' => 'Papua new Guinea', 'slug' => 'papua-new-guinea', 'phonecode' => '675', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PY', 'name' => 'Paraguay', 'slug' => 'paraguay', 'phonecode' => '595', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PE', 'name' => 'Peru', 'slug' => 'peru', 'phonecode' => '51', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PH', 'name' => 'Philippines', 'slug' => 'philippines', 'phonecode' => '63', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PN', 'name' => 'Pitcairn Island', 'slug' => 'pitcairn-island', 'phonecode' => '0', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PL', 'name' => 'Poland', 'slug' => 'poland', 'phonecode' => '48', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PT', 'name' => 'Portugal', 'slug' => 'portugal', 'phonecode' => '351', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PR', 'name' => 'Puerto Rico', 'slug' => 'puerto-rico', 'phonecode' => '1787', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'QA', 'name' => 'Qatar', 'slug' => 'qatar', 'phonecode' => '974', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'RE', 'name' => 'Reunion', 'slug' => 'reunion', 'phonecode' => '262', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'RO', 'name' => 'Romania', 'slug' => 'romania', 'phonecode' => '40', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'RU', 'name' => 'Russia', 'slug' => 'russia', 'phonecode' => '70', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'RW', 'name' => 'Rwanda', 'slug' => 'rwanda', 'phonecode' => '250', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SH', 'name' => 'Saint Helena', 'slug' => 'saint-helena', 'phonecode' => '290', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'KN', 'name' => 'Saint Kitts And Nevis', 'slug' => 'saint-kitts-and-nevis', 'phonecode' => '1869', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LC', 'name' => 'Saint Lucia', 'slug' => 'saint-lucia', 'phonecode' => '1758', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'slug' => 'saint-pierre-and-miquelon', 'phonecode' => '508', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'VC', 'name' => 'Saint Vincent And The Grenadines', 'slug' => 'saint-vincent-and-the-grenadines', 'phonecode' => '1784', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'WS', 'name' => 'Samoa', 'slug' => 'samoa', 'phonecode' => '684', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SM', 'name' => 'San Marino', 'slug' => 'san-marino', 'phonecode' => '378', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'ST', 'name' => 'Sao Tome and Principe', 'slug' => 'sao-tome-and-principe', 'phonecode' => '239', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SA', 'name' => 'Saudi Arabia', 'slug' => 'saudi-arabia', 'phonecode' => '966', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SN', 'name' => 'Senegal', 'slug' => 'senegal', 'phonecode' => '221', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'RS', 'name' => 'Serbia', 'slug' => 'serbia', 'phonecode' => '381', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SC', 'name' => 'Seychelles', 'slug' => 'seychelles', 'phonecode' => '248', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SL', 'name' => 'Sierra Leone', 'slug' => 'sierra-leone', 'phonecode' => '232', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SG', 'name' => 'Singapore', 'slug' => 'singapore', 'phonecode' => '65', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SK', 'name' => 'Slovakia', 'slug' => 'slovakia', 'phonecode' => '421', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SI', 'name' => 'Slovenia', 'slug' => 'slovenia', 'phonecode' => '386', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'XG', 'name' => 'Smaller Territories of the UK', 'slug' => 'smaller-territories-of-the-uk', 'phonecode' => '44', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SB', 'name' => 'Solomon Islands', 'slug' => 'solomon-islands', 'phonecode' => '677', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SO', 'name' => 'Somalia', 'slug' => 'somalia', 'phonecode' => '252', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'ZA', 'name' => 'South Africa', 'slug' => 'south-africa', 'phonecode' => '27', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GS', 'name' => 'South Georgia', 'slug' => 'south-georgia', 'phonecode' => '0', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SS', 'name' => 'South Sudan', 'slug' => 'south-sudan', 'phonecode' => '211', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'ES', 'name' => 'Spain', 'slug' => 'spain', 'phonecode' => '34', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'LK', 'name' => 'Sri Lanka', 'slug' => 'sri-lanka', 'phonecode' => '94', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SD', 'name' => 'Sudan', 'slug' => 'sudan', 'phonecode' => '249', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SR', 'name' => 'Suriname', 'slug' => 'suriname', 'phonecode' => '597', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SJ', 'name' => 'Svalbard And Jan Mayen Islands', 'slug' => 'svalbard-and-jan-mayen-islands', 'phonecode' => '47', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SZ', 'name' => 'Swaziland', 'slug' => 'swaziland', 'phonecode' => '268', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SE', 'name' => 'Sweden', 'slug' => 'sweden', 'phonecode' => '46', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'CH', 'name' => 'Switzerland', 'slug' => 'switzerland', 'phonecode' => '41', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'SY', 'name' => 'Syria', 'slug' => 'syria', 'phonecode' => '963', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TW', 'name' => 'Taiwan', 'slug' => 'taiwan', 'phonecode' => '886', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TJ', 'name' => 'Tajikistan', 'slug' => 'tajikistan', 'phonecode' => '992', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TZ', 'name' => 'Tanzania', 'slug' => 'tanzania', 'phonecode' => '255', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TH', 'name' => 'Thailand', 'slug' => 'thailand', 'phonecode' => '66', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TG', 'name' => 'Togo', 'slug' => 'togo', 'phonecode' => '228', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TK', 'name' => 'Tokelau', 'slug' => 'tokelau', 'phonecode' => '690', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TO', 'name' => 'Tonga', 'slug' => 'tonga', 'phonecode' => '676', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TT', 'name' => 'Trinidad And Tobago', 'slug' => 'trinidad-and-tobago', 'phonecode' => '1868', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TN', 'name' => 'Tunisia', 'slug' => 'tunisia', 'phonecode' => '216', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TR', 'name' => 'Turkey', 'slug' => 'turkey', 'phonecode' => '90', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TM', 'name' => 'Turkmenistan', 'slug' => 'turkmenistan', 'phonecode' => '7370', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TC', 'name' => 'Turks And Caicos Islands', 'slug' => 'turks-and-caicos-islands', 'phonecode' => '1649', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'TV', 'name' => 'Tuvalu', 'slug' => 'tuvalu', 'phonecode' => '688', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'UG', 'name' => 'Uganda', 'slug' => 'uganda', 'phonecode' => '256', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'UA', 'name' => 'Ukraine', 'slug' => 'ukraine', 'phonecode' => '380', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'AE', 'name' => 'United Arab Emirates', 'slug' => 'united-arab-emirates', 'phonecode' => '971', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'GB', 'name' => 'United Kingdom', 'slug' => 'united-kingdom', 'phonecode' => '44', 'status' => '1', 'priority' => '2'),
            array('sortname' => 'US', 'name' => 'United States', 'slug' => 'united-states', 'phonecode' => '1', 'status' => '1', 'priority' => '1'),
            array('sortname' => 'UM', 'name' => 'United States Minor Outlying Islands', 'slug' => 'united-states-minor-outlying-islands', 'phonecode' => '1', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'UY', 'name' => 'Uruguay', 'slug' => 'uruguay', 'phonecode' => '598', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'UZ', 'name' => 'Uzbekistan', 'slug' => 'uzbekistan', 'phonecode' => '998', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'VU', 'name' => 'Vanuatu', 'slug' => 'vanuatu', 'phonecode' => '678', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'VA', 'name' => 'Vatican City State (Holy See)', 'slug' => 'vatican-city-state-holy-see', 'phonecode' => '39', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'VE', 'name' => 'Venezuela', 'slug' => 'venezuela', 'phonecode' => '58', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'VN', 'name' => 'Vietnam', 'slug' => 'vietnam', 'phonecode' => '84', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'VG', 'name' => 'Virgin Islands (British)', 'slug' => 'virgin-islands-british', 'phonecode' => '1284', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'VI', 'name' => 'Virgin Islands (US)', 'slug' => 'virgin-islands-us', 'phonecode' => '1340', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'WF', 'name' => 'Wallis And Futuna Islands', 'slug' => 'wallis-and-futuna-islands', 'phonecode' => '681', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'EH', 'name' => 'Western Sahara', 'slug' => 'western-sahara', 'phonecode' => '212', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'YE', 'name' => 'Yemen', 'slug' => 'yemen', 'phonecode' => '967', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'YU', 'name' => 'Yugoslavia', 'slug' => 'yugoslavia', 'phonecode' => '38', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'ZM', 'name' => 'Zambia', 'slug' => 'zambia', 'phonecode' => '260', 'status' => '1', 'priority' => '0'),
            array('sortname' => 'ZW', 'name' => 'Zimbabwe', 'slug' => 'zimbabwe', 'phonecode' => '263', 'status' => '1', 'priority' => '0')
        );

        foreach ($countries as $key => $value) {
            Country::create([
                'sortname' => $value['sortname'],
                'name' => $value['name'],
                'slug' => $value['slug'],
                'phonecode' => (int) $value['phonecode'],
                'status' => (int) $value['status'],
                'priority' => (int) $value['priority']
            ]);
        }
    }

}
