

//        DB::table('countries')->insert([
//            'sortname'  => Str::random(10),
//            'name'      => Str::random(10).'@gmail.com',
//            'slug'      => Hash::make('password'),
//            'phonecode' => Hash::make('password'),
//            'status'    => Hash::make('password'),
//        ]);




['id' => 1,         'AF',	'Afghanistan',	'afghanistan',	93,	1,	NULL,	NULL],
            ['id' => 2,         'AL',	'Albania',	'albania',	355,	1,	NULL,	NULL],
            ['id' => 3,         'DZ',	'Algeria',	'algeria',	213,	1,	NULL,	NULL],
            ['id' => 4,         'AS',	'American Samoa',	'american-samoa',	1684,	1,	NULL,	NULL],
            ['id' => 5,         'AD',	'Andorra',	'andorra',	376,	1,	NULL,	NULL],
            ['id' => 6,         'AO',	'Angola',	'angola',	244,	1,	NULL,	NULL],
            ['id' => 7,         'AI',	'Anguilla',	'anguilla',	1264,	1,	NULL,	NULL],
            ['id' => 8,         'AQ',	'Antarctica',	'antarctica',	0,	1,	NULL,	NULL],
            ['id' => 9,         'AG',	'Antigua And Barbuda',	'antigua-and-barbuda',	1268,	1,	NULL,	NULL],
            
            
            
            
            
            ['id' => 10,	'AR',	'Argentina',	'argentina',	54,	1,	NULL,	NULL],
            ['id' => 11,	'AM',	'Armenia',	'armenia',	374,	1,	NULL,	NULL],
            ['id' => 12,	'AW',	'Aruba',	'aruba',	297,	1,	NULL,	NULL],
            ['id' => 13,	'AU',	'Australia',	'australia',	61,	1,	NULL,	NULL],
            ['id' => 14,	'AT',	'Austria',	'austria',	43,	1,	NULL,	NULL],
            ['id' => 15,	'AZ',	'Azerbaijan',	'azerbaijan',	994,	1,	NULL,	NULL],
            ['id' => 16,	'BS',	'Bahamas The',	'bahamas-the',	1242,	1,	NULL,	NULL],
            ['id' => 17,	'BH',	'Bahrain',	'bahrain',	973,	1,	NULL,	NULL],
            ['id' => 18,	'BD',	'Bangladesh',	'bangladesh',	880,	1,	NULL,	NULL],
            ['id' => 19,	'BB',	'Barbados',	'barbados',	1246,	1,	NULL,	NULL],
            ['id' => 20,	'BY',	'Belarus',	'belarus',	375,	1,	NULL,	NULL],
            ['id' => 21,	'BE',	'Belgium',	'belgium',	32,	1,	NULL,	NULL],
            ['id' => 22,	'BZ',	'Belize',	'belize',	501,	1,	NULL,	NULL],
            ['id' => 23,	'BJ',	'Benin',	'benin',	229,	1,	NULL,	NULL],
            ['id' => 24,	'BM',	'Bermuda',	'bermuda',	1441,	1,	NULL,	NULL],
            ['id' => 25,	'BT',	'Bhutan',	'bhutan',	975,	1,	NULL,	NULL],
            ['id' => 26,	'BO',	'Bolivia',	'bolivia',	591,	1,	NULL,	NULL],
            ['id' => 27,	'BA',	'Bosnia and Herzegovina',	'bosnia-and-herzegovina',	387,	1,	NULL,	NULL],
            ['id' => 28,	'BW',	'Botswana',	'botswana',	267,	1,	NULL,	NULL],
            ['id' => 29,	'BV',	'Bouvet Island',	'bouvet-island',	0,	1,	NULL,	NULL],
            ['id' => 30,	'BR',	'Brazil',	'brazil',	55,	1,	NULL,	NULL],
            ['id' => 31,	'IO',	'British Indian Ocean Territory',	'british-indian-ocean-territory',	246,	1,	NULL,	NULL],
            ['id' => 32,	'BN',	'Brunei',	'brunei',	673,	1,	NULL,	NULL],
            ['id' => 33,	'BG',	'Bulgaria',	'bulgaria',	359,	1,	NULL,	NULL],
            ['id' => 34,	'BF',	'Burkina Faso',	'burkina-faso',	226,	1,	NULL,	NULL],
            ['id' => 35,	'BI',	'Burundi',	'burundi',	257,	1,	NULL,	NULL],
            ['id' => 36,	'KH',	'Cambodia',	'cambodia',	855,	1,	NULL,	NULL],
            ['id' => 37,	'CM',	'Cameroon',	'cameroon',	237,	1,	NULL,	NULL],
            ['id' => 38,	'CA',	'Canada',	'canada',	1,	1,	NULL,	NULL],
            ['id' => 39,	'CV',	'Cape Verde',	'cape-verde',	238,	1,	NULL,	NULL],
            ['id' => 40,	'KY',	'Cayman Islands',	'cayman-islands',	1345,	1,	NULL,	NULL],
            ['id' => 41,	'CF',	'Central African Republic',	'central-african-republic',	236,	1,	NULL,	NULL],
            ['id' => 42,	'TD',	'Chad',	'chad',	235,	1,	NULL,	NULL],
            ['id' => 43,	'CL',	'Chile',	'chile',	56,	1,	NULL,	NULL],
            ['id' => 44,	'CN',	'China',	'china',	86,	1,	NULL,	NULL],
            ['id' => 45,	'CX',	'Christmas Island',	'christmas-island',	61,	1,	NULL,	NULL],
            ['id' => 46,	'CC',	'Cocos (Keeling) Islands',	'cocos-keeling-islands',	672,	1,	NULL,	NULL],
            ['id' => 47,	'CO',	'Colombia',	'colombia',	57,	1,	NULL,	NULL],
            ['id' => 48,	'KM',	'Comoros',	'comoros',	269,	1,	NULL,	NULL],
            ['id' => 49,	'CG',	'Republic Of The Congo',	'republic-of-the-congo',	242,	1,	NULL,	NULL],
            ['id' => 50,	'CD',	'Democratic Republic Of The Congo',	'democratic-republic-of-the-congo',	242,	1,	NULL,	NULL],
            ['id' => 51,	'CK',	'Cook Islands',	'cook-islands',	682,	1,	NULL,	NULL],
            ['id' => 52,	'CR',	'Costa Rica',	'costa-rica',	506,	1,	NULL,	NULL],
            ['id' => 53,	'CI',	'Cote D\'Ivoire (Ivory Coast)',	'cote-divoire-ivory-coast',	225,	1,	NULL,	NULL],
            ['id' => 54,	'HR',	'Croatia (Hrvatska)',	'croatia-hrvatska',	385,	1,	NULL,	NULL],
            ['id' => 55,	'CU',	'Cuba',	'cuba',	53,	1,	NULL,	NULL],
            ['id' => 56,	'CY',	'Cyprus',	'cyprus',	357,	1,	NULL,	NULL],
            ['id' => 57,	'CZ',	'Czech Republic',	'czech-republic',	420,	1,	NULL,	NULL],
            ['id' => 58,	'DK',	'Denmark',	'denmark',	45,	1,	NULL,	NULL],
            ['id' => 59,	'DJ',	'Djibouti',	'djibouti',	253,	1,	NULL,	NULL],
            ['id' => 60,	'DM',	'Dominica',	'dominica',	1767,	1,	NULL,	NULL],
            ['id' => 61,	'DO',	'Dominican Republic',	'dominican-republic',	1809,	1,	NULL,	NULL],
            ['id' => 62,	'TP',	'East Timor',	'east-timor',	670,	1,	NULL,	NULL],
            ['id' => 63,	'EC',	'Ecuador',	'ecuador',	593,	1,	NULL,	NULL],
            ['id' => 64,	'EG',	'Egypt',	'egypt',	20,	1,	NULL,	NULL],
            ['id' => 65,	'SV',	'El Salvador',	'el-salvador',	503,	1,	NULL,	NULL],
            ['id' => 66,	'GQ',	'Equatorial Guinea',	'equatorial-guinea',	240,	1,	NULL,	NULL],
            ['id' => 67,	'ER',	'Eritrea',	'eritrea',	291,	1,	NULL,	NULL],
            ['id' => 68,	'EE',	'Estonia',	'estonia',	372,	1,	NULL,	NULL],
            ['id' => 69,	'ET',	'Ethiopia',	'ethiopia',	251,	1,	NULL,	NULL],
            ['id' => 70,	'XA',	'External Territories of Australia',	'external-territories-of-australia',	61,	1,	NULL,	NULL],
            ['id' => 71,	'FK',	'Falkland Islands',	'falkland-islands',	500,	1,	NULL,	NULL],
            ['id' => 72,	'FO',	'Faroe Islands',	'faroe-islands',	298,	1,	NULL,	NULL],
            ['id' => 73,	'FJ',	'Fiji Islands',	'fiji-islands',	679,	1,	NULL,	NULL],
            ['id' => 74,	'FI',	'Finland',	'finland',	358,	1,	NULL,	NULL],
            ['id' => 75,	'FR',	'France',	'france',	33,	1,	NULL,	NULL],
            ['id' => 76,	'GF',	'French Guiana',	'french-guiana',	594,	1,	NULL,	NULL],
            ['id' => 77,	'PF',	'French Polynesia',	'french-polynesia',	689,	1,	NULL,	NULL],
            ['id' => 78,	'TF',	'French Southern Territories',	'french-southern-territories',	0,	1,	NULL,	NULL],
            ['id' => 79,	'GA',	'Gabon',	'gabon',	241,	1,	NULL,	NULL],
            ['id' => 80,	'GM',	'Gambia The',	'gambia-the',	220,	1,	NULL,	NULL],
            ['id' => 81,	'GE',	'Georgia',	'georgia',	995,	1,	NULL,	NULL],
            ['id' => 82,	'DE',	'Germany',	'germany',	49,	1,	NULL,	NULL],
            ['id' => 83,	'GH',	'Ghana',	'ghana',	233,	1,	NULL,	NULL],
            ['id' => 84,	'GI',	'Gibraltar',	'gibraltar',	350,	1,	NULL,	NULL],
            ['id' => 85,	'GR',	'Greece',	'greece',	30,	1,	NULL,	NULL],
            ['id' => 86,	'GL',	'Greenland',	'greenland',	299,	1,	NULL,	NULL],
            ['id' => 87,	'GD',	'Grenada',	'grenada',	1473,	1,	NULL,	NULL],
            ['id' => 88,	'GP',	'Guadeloupe',	'guadeloupe',	590,	1,	NULL,	NULL],
            ['id' => 89,	'GU',	'Guam',	'guam',	1671,	1,	NULL,	NULL],
            ['id' => 90,	'GT',	'Guatemala',	'guatemala',	502,	1,	NULL,	NULL],
            ['id' => 91,	'XU',	'Guernsey and Alderney',	'guernsey-and-alderney',	44,	1,	NULL,	NULL],
            ['id' => 92,	'GN',	'Guinea',	'guinea',	224,	1,	NULL,	NULL],
            ['id' => 93,	'GW',	'Guinea-Bissau',	'guineabissau',	245,	1,	NULL,	NULL],
            ['id' => 94,	'GY',	'Guyana',	'guyana',	592,	1,	NULL,	NULL],
            ['id' => 95,	'HT',	'Haiti',	'haiti',	509,	1,	NULL,	NULL],
            ['id' => 96,	'HM',	'Heard and McDonald Islands',	'heard-and-mcdonald-islands',	0,	1,	NULL,	NULL],
            ['id' => 97,	'HN',	'Honduras',	'honduras',	504,	1,	NULL,	NULL],
            ['id' => 98,	'HK',	'Hong Kong S.A.R.',	'hong-kong-sar',	852,	1,	NULL,	NULL],
            ['id' => 99,	'HU',	'Hungary',	'hungary',	36,	1,	NULL,	NULL],